import '../models/video.dart';
import '../models/channel.dart';

class MockDataService {
  static List<Channel> getInitialChannels() {
    return [
      Channel(
        id: 'UCsBjURrPoezykLs9EqgamOA',
        title: 'Fireship Dev',
        handle: '@fireship',
        avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
        verified: true,
        videoCount: 84,
        description: 'High-intensity code tutorials to help you ship apps faster.',
        unreadCount: 3,
        latestVideoTime: '2h ago',
        subscriberCount: '3.1M subscribers',
        isFavorite: true,
      ),
      Channel(
        id: 'UCvjgXvBlbQiydffZU7m1_aw',
        title: 'The Coding Train',
        handle: '@thecodingtrain',
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
        verified: true,
        videoCount: 142,
        description: 'Creative coding tutorials on algorithms, physics simulation, and shaders.',
        unreadCount: 1,
        latestVideoTime: '1d ago',
        isFavorite: true,
      ),
      Channel(
        id: 'UC8butISFwT-Wl7EV0hUK0BQ',
        title: 'freeCodeCamp.org',
        handle: '@freecodecamp',
        avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
        verified: true,
        videoCount: 320,
        description: 'Learn to code for free with full comprehensive masterclasses.',
        unreadCount: 4,
        latestVideoTime: '3h ago',
      ),
      Channel(
        id: 'UCbfYPyITQ-7l4upoX8nvctg',
        title: 'Two Minute Papers',
        handle: '@twominutepapers',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
        verified: true,
        videoCount: 68,
        description: 'What a time to be alive! Weekly deep-dives into cutting-edge AI research.',
        unreadCount: 2,
        latestVideoTime: '6h ago',
      ),
      Channel(
        id: 'UCHnyfMqiRRG1u-2MsSQLbXA',
        title: 'Veritasium',
        handle: '@veritasium',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        verified: true,
        videoCount: 94,
        description: 'An element of truth - videos about science, education, and curiosity.',
        unreadCount: 0,
        latestVideoTime: '3d ago',
      ),
    ];
  }

  static List<Video> getInitialVideos() {
    return [
      Video(
        id: 'vid-1',
        youtubeVideoId: 'dQw4w9WgXcQ',
        title: 'Building an Autonomous AI Agent Pipeline in Rust & WASM',
        channelTitle: 'Fireship Dev',
        channelAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
        channelVerified: true,
        channelId: 'UCsBjURrPoezykLs9EqgamOA',
        thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
        duration: '18:42',
        durationSeconds: 1122,
        publishedAt: '2025-10-14T10:00:00Z',
        relativeTime: '2 hours ago',
        category: 'Tech & Dev',
        description: 'A high-efficiency deep dive into building deterministic multi-threaded AI pipelines compiled into WebAssembly targets using native Rust concurrency channels.',
        views: '24.5k views',
        chapters: [
          Chapter(title: 'Introduction & Multi-Agent Dilemma', time: '00:00', seconds: 0),
          Chapter(title: 'Memory Architecture & Tokio Channels', time: '03:15', seconds: 195),
          Chapter(title: 'Rust Code Walkthrough & WASM Build', time: '09:40', seconds: 580),
          Chapter(title: 'Benchmark Runs vs Python Asyncio', time: '15:20', seconds: 920),
        ],
        tags: ['rustlang', 'wasm', 'agent-ops', 'ai'],
      ),
      Video(
        id: 'vid-2',
        youtubeVideoId: 'L_LUpnjgPso',
        title: 'Why Postgres Vector Indexes Beat Dedicated Databases at Scale',
        channelTitle: 'Fireship Dev',
        channelAvatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
        channelVerified: true,
        channelId: 'UCsBjURrPoezykLs9EqgamOA',
        thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
        duration: '12:18',
        durationSeconds: 738,
        publishedAt: '2025-10-14T08:00:00Z',
        relativeTime: '4 hours ago',
        category: 'Tech & Dev',
        description: 'Benchmarking pgvector HNSW vs Pinecone and Milvus for 10M embeddings with real ACID guarantees.',
        views: '38.1k views',
        tags: ['postgres', 'pgvector', 'databases'],
      ),
      Video(
        id: 'vid-3',
        youtubeVideoId: '8pTEmbeENF4',
        title: 'This New AI Video Model Just Blew Everyone Away in 2 Minutes',
        channelTitle: 'Two Minute Papers',
        channelAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
        channelVerified: true,
        channelId: 'UCbfYPyITQ-7l4upoX8nvctg',
        thumbnail: 'https://images.unsplash.com/photo-1618172193763-c511deb635ca?w=800&auto=format&fit=crop&q=80',
        duration: '06:14',
        durationSeconds: 374,
        publishedAt: '2025-10-14T06:00:00Z',
        relativeTime: '6 hours ago',
        category: 'Science',
        description: 'Examining the latest neural diffusion transformer research paper producing coherent 60fps physics simulations.',
        views: '115k views',
        tags: ['ai', 'research', 'deeplearning'],
      ),
      Video(
        id: 'vid-4',
        youtubeVideoId: 'aircAruvnKk',
        title: 'Full Stack Flutter 3.22 & Go Backend Masterclass (Zero to Production)',
        channelTitle: 'freeCodeCamp.org',
        channelAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
        channelVerified: true,
        channelId: 'UC8butISFwT-Wl7EV0hUK0BQ',
        thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
        duration: '4:15:30',
        durationSeconds: 15330,
        publishedAt: '2025-10-13T18:00:00Z',
        relativeTime: '1 day ago',
        category: 'Tech & Dev',
        description: 'Comprehensive 4-hour tutorial building cross-platform Android, iOS, and Web clients in Flutter connected to a high-speed Go REST & WebSocket API.',
        views: '190k views',
        tags: ['flutter', 'golang', 'fullstack'],
      ),
    ];
  }
}
